# Was under /usr/local/apache/conf/userdata/std/2/trioomph
<IfModule mod_alias.c>
Alias /robots.txt /home/trioomph/trioomphproject/robots.txt
Alias /site_media /home/trioomph/trioomphproject/trioomph/trioomph/files
Alias /admin_media /home/trioomph/trioomphproject/lib/python2.7/site-packages/django/contrib/admin/static/admin
</IfModule>

<IfModule mod_wsgi.c>
WSGIScriptAlias / /home/trioomph/trioomphproject/trioomph/trioomph/wsgi.py
WSGIDaemonProcess trioomph processes=7 threads=1 display-name=%{GROUP} python-path=/home/trioomph/trioomphproject/trioomph:/home/trioomph/trioomphproject/trioomph/trioomph/:/home/trioomph/trioomphproject/lib/python2.7/site-packages/
WSGIProcessGroup trioomph
WSGIApplicationGroup %{GLOBAL} 
</IfModule>

# This fixes the broken ErrorDocument directive we inherit that breaks auth
# if we use a WSGI app.
ErrorDocument 401 "Authentication Error"
ErrorDocument 403 "Forbidden"
